In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv("powerplant _dataset.csv")

In [4]:
df.head()
# AT- TEMPERATURE
# V- VACCUM
# AP-PRESSURE
# RH- HUMIDITY
# PE- PRODUCE ENERGY

      AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [3]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [4]:
X= df.drop("PE",axis=1)
y=df['PE']

In [5]:
X

         AT      V       AP     RH
0      8.34  40.77  1010.84  90.01
1     23.64  58.49  1011.40  74.20
2     29.74  56.90  1007.15  41.91
3     19.07  49.69  1007.22  76.79
4     11.80  40.66  1017.13  97.20
...     ...    ...      ...    ...
9563  15.12  48.92  1011.80  72.93
9564  33.41  77.95  1010.30  59.72
9565  15.99  43.34  1014.20  78.66
9566  17.65  59.87  1018.58  94.65
9567  23.68  51.30  1011.86  71.24

[9568 rows x 4 columns]

In [7]:
# Split out the data
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2, random_state=42)

In [8]:
df.shape

(9568, 5)

In [9]:
from sklearn.preprocessing import StandardScaler

scalar= StandardScaler()

x_train_scaled= scalar.fit_transform(X_train)
x_test_scaled= scalar.transform(X_test)

### Convert data into tensors